title: 能耗优化参数配置工具
api-tools:
  全局服务地址: 172.16.134.122
  平台端口: '8900'
  接口协议类型: http
  api-key: 
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6IjAwMiJ9.eyJ0ZW5hbnROYW0iOiLnp5_miLfnrqHnkIblhazlj7giLCJvcmdOYW1lIjoi5piG6ZKiIiwiaXNzIjoiU1lTIiwidXNyUm9sZSI6IkdHU0NHTCIsInNlbGVjdGVkT3JnIjoiMTg1ODc4MTAxMjU1MzYyOTY5NiIsImFkbWluRmxnIjoiMSIsIm9yZ0lkIjoiMTg1ODc5NjUzODkxNDkzMDY4OCIsInVzck5hbSI6Iuezu-e7n-euoeeQhuWRmCIsInRlbmFudE5vIjoiMSIsIndlYlNvY2tldElwIjoiZGVmYXVsdCIsImlhdCI6MTc0OTc5NDIwMSwia2F0IjoxNzQ5Nzc0NDUwODM5fQ.rM7KBJ_UrLfriScotpdMNUspcR0xonyFM-d2NnWHLiw
  nacos:
    port: '8849'
    username: nacos
    password: Luculent@2023!
    namespace: test-nhyh
  api:
    file_upload:
      type: file-upload
      upload_path: /rest/di/dataset/upload
      add_path: /rest/di/dataset/add
    model_upload:
      type: model-upload
      upload_path: /rest/di/flow/importModelFlow
      del_path: /rest/di/flow/del
      env_path: /rest/di/env/linkFlow
    model_duplicate:
      type: model-duplicate
      copy_path: /rest/di/template/use
      model_info: /rest/di/flow/info
      env_path: /rest/di/env/linkFlow
    model_execute:
      type: model-execute
      copy_path: /rest/di/flow/run
    model_logger:
      type: model-logger
      log_path: /rest/di/flow/node/data
    service_list:
      type: services-list
      service_list_path: 
        /rest/di/service/hall?page=1&limit=1000&searchText=&orderBy=
    service_params:
      type: services-params
      service_params_path: 
        /rest/di/service/param/list?limit=1000&searchText=&paramForm=0&orderBy=
    service_logger:
      type: services-logs
      service_state_path: /rest/di/service/detail
      service_log_path: /rest/di/service/serviceLog
    service_reonline:
      type: services-reonline
      service_online_path: /rest/di/service/online
      service_outline_path: /rest/di/service/outline
    point_search:
      type: point-search
      dev_name_path: /rest/fm/fms10001/listSearchTree
      tag_info_search: /rest/database/sis/searchTagInfo
      point_path:
        通用参数: 
          /rest/eng/paramConfig/listParamNew?page=1&limit=1000&searchText=&pctypType=5&paramType=01&orderBy=&devNo=
        工况参数: 
          /rest/eng/paramConfig/listParamNew?page=1&limit=1000&searchText=&pctypType=5&paramType=02&orderBy=&devNo=
        控制参数: 
          /rest/eng/paramConfig/listParamNew?page=1&limit=1000&searchText=&pctypType=5&paramType=03&orderBy=&devNo=
        环境参数: 
          /rest/eng/paramConfig/listParamNew?page=1&limit=1000&searchText=&pctypType=5&paramType=04&orderBy=&devNo=
        时序库参数: /rest/database/queryList?page=1&limit=100000&searchText=&orderBy=
    rtsp_search:
      type: rtsp-search
      dev_name_path: /rest/fm/fms10001/listSearchTree
      point_path:
        视频流地址: 
          /rest/video/camera/config/selectCameraList4VR?page=1&limit=1000&searchText=&eqlevelTyp=3&orderBy=&eqlevelNo=
    trenddb_fetcher:
      type: trenddb-fetcher
      path: /rest/database/sis/getSeriesValuesByNameList?span=2&dataMode=3
param-structure:
  控制参数:
    type: subgroup
    subchildren:
      测点名:
        type: fetch
        options:
        - point_search
      控制范围:
        type: range
      理论正常范围:
        type: range
      控制类型:
        type: dropdown
        default: 频率
        options:
        - 频率
        - 风门开度
        - 统一频率
      偏移量:
        type: slider
        default: '0'
        options:
        - '-5'
        - '5'
        - '1'
  目标参数:
    type: subgroup
    subchildren:
      测点名:
        type: fetch
        options:
        - point_search
      目标计算类型:
        type: dropdown
        default: 最小
        options:
        - 最小
        - 最大
        - 均值+上下限
        - 均值+上限
        - 均值+下限
        - 均值
      理论正常范围:
        type: range
  工况参数:
    type: subgroup
    subchildren:
      测点名:
        type: fetch
        options:
        - point_search
      理论正常范围:
        type: range
      工况类型:
        type: dropdown
        default: 开关量
        options:
        - 开关量
        - 模拟量
      切分数量:
        type: text
        default: ''
      自定义切分范围:
        type: partition
        default: ''
  工况划分策略:
    type: dropdown
    default: 距离匹配
    options:
    - 距离匹配
    - 聚类匹配
  寻优范围计算方法:
    type: dropdown
    default: 自适应
    options:
    - 自适应
    - 众数-6%
    - 众数-10%
    - 均值-10%
    - 均值-6%
    - 下四分位距
    - 正态分布
  聚类数量:
    type: text
    default: ''
  是否保留工况:
    type: checkbox
    default: 否
    options:
    - 否
    - 是
  新工况判断阈值:
    type: slider
    default: '1.5'
    options:
    - '0'
    - '3'
    - '2'
  实时训练数据范围(天):
    type: slider
    default: '0'
    options:
    - '0'
    - '40'
    - '0'
  实时训练数据采样间隔(s):
    type: slider
    default: '60'
    options:
    - '20'
    - '120'
    - '0'
  历史训练数据范围:
    type: subgroup
    subchildren:
      开始/结束时间:
        type: time_range_select
        default: ''
      采样间隔(s):
        type: slider
        default: '60'
        options:
        - '20'
        - '120'
        - '0'
  时序库配置:
    type: group
    children:
      时序库host:
        type: text
        default: ''
      时序库版本:
        type: dropdown
        default: V4
        options:
        - V4
        - V5
      时序库port:
        type: text
        default: ''
      时序库库名:
        type: text
        default: ''
      时序库用户名(V4不需要):
        type: text
        default: ''
      时序库密码(V4不需要):
        type: text
        default: ''
  新工况控制模式:
    type: dropdown
    default: 三个最近工况高频
    options:
    - 所有数据高频
    - 三个最近工况高频
    - 给定频率
  视频参数:
    type: group
    children:
      测点名:
        type: fetch
        options:
        - point_search
      视频流地址:
        type: fetch
        options:
        - rtsp_search
      识别种类:
        type: text
        default: smoke
      平台地址:
        type: text
      运行设备:
        type: dropdown
        default: cpu
        options:
        - cpu
        - '0'
  新工况控制模式2:
    type: dropdown
    default: 三个最近工况高频
    options:
    - 所有数据高频
    - 三个最近工况高频
    - 给定频率
param-template:
  text:
    name: 文本编辑
    params:
    - default
  checkbox:
    name: 复选框
    params:
    - default
    - options
    params_default:
    - ''
    - - 下拉选项
  dropdown:
    name: 下拉框
    params:
    - default
    - options
    params_default:
    - ''
    - - 下拉选项
  multiselect_dropdown:
    name: 多选下拉框
    params:
    - default
    - options
    params_default:
    - ''
    - - 下拉选项
  fetch:
    name: 测点接口数据
    params:
    - options
    params_type:
    - list
    params_default:
    - - 测点获取接口
  range:
    name: 范围选择
    params:
    - default
  partition:
    name: 分区选择
    params:
    - default
  time_range_select:
    name: 训练数据框选
  slider:
    name: 滑块
    params:
    - default
    - options
    params_default:
    - ''
    - - 下限
      - 上限
      - 小数点位
  time:
    name: 时间选择
  group:
    name: 参数组
    params:
    - children
    params_default:
    - {}
  subgroup:
    name: 预制参数组
    params:
    - subchildren
    params_default:
    - {}
version-control:
  版本管理方式: gitcode
  gitee:
    项目名称: dingmama123141/JsonConfiguration
    令牌: token 577df5e6829a600271587e1af4793fb7
  github:
    项目名称: martin98-afk/JsonConfiguration
  gitcode:
    项目名称: mading12315/JsonConfiguration
    令牌: J9r98fXvxywspbdivTje2yQM
tab-names:
  api-tools: 接口参数配置
  param-structure: 参数结构配置
  param-template: 参数初始化模板
  version-control: 版本控制配置
  title: 工具标题设置
  tab-names: 配置名称设置
